CREATE TABLE invoice(
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    id_card BIGINT,
    amount_due DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    date_due DATE NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_card FOREIGN KEY(id_card) REFERENCES card(id) ON DELETE CASCADE
)